import React,{Component} from 'react'
import Banner from '../components/Banner.js'
import Button from '../components/Button.js'
import TitleCenter from '../components/TitleCenter.js'

class ColorPalettePage extends Component {
  constructor(props){
    super(props);
    this.state={
      varColor:'',
      colorCodes : [
    {
      colorNumber:1,
      colorPot:'bg-[#f9fafa]',
      colorName: 'GA01C8-P',
      colorGroup:'black',
    },
    {
      colorNumber:2,
      colorPot:'bg-[#eaf1f7]',
      colorName: 'GA01C7-P',
      colorGroup:'black',
    },
    {
      colorNumber:3,
      colorPot:'bg-[#d5e0ea]',
      colorName: 'GA01C6-P',
      colorGroup:'black',
    },
    {
      colorNumber:4,
      colorPot:'bg-[#b5c3cd]',
      colorName: 'GA01C5-K',
      colorGroup:'black',
    },
    {
      colorNumber:5,
      colorPot:'bg-[#919da7]',
      colorName: 'GA01C4-T',
      colorGroup:'black',
    },
    {
      colorNumber:6,
      colorPot:'bg-[#62717d]',
      colorName: 'GA01C3-D',
      colorGroup:'black',
    },
    {
      colorNumber:7,
      colorPot:'bg-[#3e474c]',
      colorName: 'GA01C2-A',
      colorGroup:'black',
    },
    {
      colorNumber:8,
      colorPot:'bg-[#373a3b]',
      colorName: 'GA01C1-A',
      colorGroup:'black',
    },
    {
      colorNumber:9,
      colorPot:'bg-[#f3f9fc]',
      colorName: 'GA02C8-P',
      colorGroup:'black',
    },
    {
      colorNumber:10,
      colorPot:'bg-[#e4f1fb]',
      colorName: 'GA02C7-P',
      colorGroup:'black',
    },
    {
      colorNumber:11,
      colorPot:'bg-[#d5e7f4]',
      colorName: 'GA02C6-P',
      colorGroup:'black',
    },
    {
      colorNumber:12,
      colorPot:'bg-[#c4d6e4]',
      colorName: 'GA02C5-P',
      colorGroup:'black',
    },
    {
      colorNumber:13,
      colorPot:'bg-[#a2b4c2]',
      colorName: 'GA02C4-T',
      colorGroup:'black',
    },
    {
      colorNumber:14,
      colorPot:'bg-[#738595]',
      colorName: 'GA02C3-D',
      colorGroup:'black',
    },
    {
      colorNumber:15,
      colorPot:'bg-[#4b5c6d]',
      colorName: 'GA02C2-A',
      colorGroup:'black',
    },
    {
      colorNumber:16,
      colorPot:'bg-[#4d5359]',
      colorName: 'GA02C1-A',
      colorGroup:'black',
    },
    {
      colorNumber:17,
      colorPot:'bg-[#f9fdfe]',
      colorName: 'GA03C8-P',
      colorGroup:'black',
    },
    {
      colorNumber:18,
      colorPot:'bg-[#ecf7fc]',
      colorName: 'GA03C7-P',
      colorGroup:'black',
    },
    {
      colorNumber:19,
      colorPot:'bg-[#deeef6]',
      colorName: 'GA03C6-P',
      colorGroup:'black',
    },
    {
      colorNumber:20,
      colorPot:'bg-[#b1cad2]',
      colorName: 'GA03C5-K',
      colorGroup:'black',
    },
    {
      colorNumber:21,
      colorPot:'bg-[#8ea5ad]',
      colorName: 'GA03C4-T',
      colorGroup:'black',
    },
    {
      colorNumber:22,
      colorPot:'bg-[#647d84]',
      colorName: 'GA03C3-D',
      colorGroup:'black',
    },
    {
      colorNumber:23,
      colorPot:'bg-[#465c5c]',
      colorName: 'GA03C2-A',
      colorGroup:'black',
    },
    {
      colorNumber:24,
      colorPot:'bg-[#4c5153]',
      colorName: 'GA03C1-A',
      colorGroup:'black',
    },
    {
      colorNumber:25,
      colorPot:'bg-[#f9f8fb]',
      colorName: 'GA04C8-P',
      colorGroup:'black',
    },
    {
      colorNumber:26,
      colorPot:'bg-[#efeff5]',
      colorName: 'GA04C7-P',
      colorGroup:'black',
    },
    {
      colorNumber:27,
      colorPot:'bg-[#d9dbe2]',
      colorName: 'GA04C6-P',
      colorGroup:'black',
    },
    {
      colorNumber:28,
      colorPot:'bg-[#cecbd2]',
      colorName: 'GA04C5-K',
      colorGroup:'black',
    },
    {
      colorNumber:29,
      colorPot:'bg-[#aaa8ae]',
      colorName: 'GA04C4-T',
      colorGroup:'black',
    },
    {
      colorNumber:30,
      colorPot:'bg-[#666162]',
      colorName: 'GA04C3-D',
      colorGroup:'black',
    },
    {
      colorNumber:31,
      colorPot:'bg-[#5b5657]',
      colorName: 'GA04C2-A',
      colorGroup:'black',
    },
    {
      colorNumber:32,
      colorPot:'bg-[#4d4949]',
      colorName: 'GA04C1-A',
      colorGroup:'black',
    },
    {
      colorNumber:33,
      colorPot:'bg-[#fffdfc]',
      colorName: 'GA05C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:34,
      colorPot:'bg-[#f6f2f4]',
      colorName: 'GA05C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:35,
      colorPot:'bg-[#e6e0e2]',
      colorName: 'GA05C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:36,
      colorPot:'bg-[#cfc6ca]',
      colorName: 'GA05C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:37,
      colorPot:'bg-[#b3a5ab]',
      colorName: 'GA05C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:38,
      colorPot:'bg-[#806f72]',
      colorName: 'GA05C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:39,
      colorPot:'bg-[#664f4b]',
      colorName: 'GA05C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:40,
      colorPot:'bg-[#5c4a4a]',
      colorName: 'GA05C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:41,
      colorPot:'bg-[#fffcfd]',
      colorName: 'GA06C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:42,
      colorPot:'bg-[#fdf8fa]',
      colorName: 'GA06C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:43,
      colorPot:'bg-[#e8dde4]',
      colorName: 'GA06C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:44,
      colorPot:'bg-[#cabbc4]',
      colorName: 'GA06C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:45,
      colorPot:'bg-[#a6949d]',
      colorName: 'GA06C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:46,
      colorPot:'bg-[#7e6367]',
      colorName: 'GA06C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:47,
      colorPot:'bg-[#5d3835]',
      colorName: 'GA06C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:48,
      colorPot:'bg-[#593a37]',
      colorName: 'GA06C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:49,
      colorPot:'bg-[#fefafa]',
      colorName: 'GA07C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:50,
      colorPot:'bg-[#f5eaed]',
      colorName: 'GA07C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:51,
      colorPot:'bg-[#ecdde2]',
      colorName: 'GA07C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:52,
      colorPot:'bg-[#d7bdc3]',
      colorName: 'GA07C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:53,
      colorPot:'bg-[#c19193]',
      colorName: 'GA07C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:54,
      colorPot:'bg-[#a66261]',
      colorName: 'GA07C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:55,
      colorPot:'bg-[#924b44]',
      colorName: 'GA07C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:56,
      colorPot:'bg-[#87463b]',
      colorName: 'GA07C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:57,
      colorPot:'bg-[#fffcfb]',
      colorName: 'GA08C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:58,
      colorPot:'bg-[#fef8f7]',
      colorName: 'GA08C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:59,
      colorPot:'bg-[#fdeeeb]',
      colorName: 'GA08C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:60,
      colorPot:'bg-[#f9dcd0]',
      colorName: 'GA08C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:61,
      colorPot:'bg-[#e1b8a6]',
      colorName: 'GA08C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:62,
      colorPot:'bg-[#bb795f]',
      colorName: 'GA08C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:63,
      colorPot:'bg-[#a96249]',
      colorName: 'GA08C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:64,
      colorPot:'bg-[#a6614b]',
      colorName: 'GA08C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:65,
      colorPot:'bg-[#fffdfa]',
      colorName: 'GA09C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:66,
      colorPot:'bg-[#fcf8f8]',
      colorName: 'GA09C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:67,
      colorPot:'bg-[#faf1ee]',
      colorName: 'GA09C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:68,
      colorPot:'bg-[#efd9c8]',
      colorName: 'GA09C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:69,
      colorPot:'bg-[#debe9c]',
      colorName: 'GA09C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:70,
      colorPot:'bg-[#c39267]',
      colorName: 'GA09C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:71,
      colorPot:'bg-[#b9804c]',
      colorName: 'GA09C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:72,
      colorPot:'bg-[#a66843]',
      colorName: 'GA09C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:73,
      colorPot:'bg-[#fffdfa]',
      colorName: 'GA10C8-P',
      colorGroup:'red',
    },
    {
      colorNumber:74,
      colorPot:'bg-[#fcf8f5]',
      colorName: 'GA10C7-P',
      colorGroup:'red',
    },
    {
      colorNumber:75,
      colorPot:'bg-[#f3ece4]',
      colorName: 'GA10C6-P',
      colorGroup:'red',
    },
    {
      colorNumber:76,
      colorPot:'bg-[#ded3cb]',
      colorName: 'GA10C5-K',
      colorGroup:'red',
    },
    {
      colorNumber:77,
      colorPot:'bg-[#b69b8a]',
      colorName: 'GA10C4-T',
      colorGroup:'red',
    },
    {
      colorNumber:78,
      colorPot:'bg-[#896a56]',
      colorName: 'GA10C3-D',
      colorGroup:'red',
    },
    {
      colorNumber:79,
      colorPot:'bg-[#705241]',
      colorName: 'GA10C2-A',
      colorGroup:'red',
    },
    {
      colorNumber:80,
      colorPot:'bg-[#795241]',
      colorName: 'GA10C1-A',
      colorGroup:'red',
    },
    {
      colorNumber:81,
      colorPot:'bg-[#fffdfa]',
      colorName: 'GA11C8-P',
      colorGroup:'brown',
    },
    {
      colorNumber:82,
      colorPot:'bg-[#fbf8f7]',
      colorName: 'GA11C7-P',
      colorGroup:'brown',
    },
    {
      colorNumber:83,
      colorPot:'bg-[#e8e3de]',
      colorName: 'GA11C6-P',
      colorGroup:'brown',
    },
    {
      colorNumber:84,
      colorPot:'bg-[#ccc3b8]',
      colorName: 'GA11C5-K',
      colorGroup:'brown',
    },
    {
      colorNumber:85,
      colorPot:'bg-[#c0b1a1]',
      colorName: 'GA11C4-T',
      colorGroup:'brown',
    },
    {
      colorNumber:86,
      colorPot:'bg-[#a79482]',
      colorName: 'GA11C3-D',
      colorGroup:'brown',
    },
    {
      colorNumber:87,
      colorPot:'bg-[#6e5447]',
      colorName: 'GA11C2-A',
      colorGroup:'brown',
    },
    {
      colorNumber:88,
      colorPot:'bg-[#655745]',
      colorName: 'GA11C1-A',
      colorGroup:'brown',
    },
    {
      colorNumber:89,
      colorPot:'bg-[#fffdfa]',
      colorName: 'GA12C8-P',
      colorGroup:'brown',
    },
    {
      colorNumber:90,
      colorPot:'bg-[#fffcf5]',
      colorName: 'GA12C7-P',
      colorGroup:'brown',
    },
    {
      colorNumber:91,
      colorPot:'bg-[#fef7ea]',
      colorName: 'GA12C6-P',
      colorGroup:'brown',
    },
    {
      colorNumber:92,
      colorPot:'bg-[#f6e9cf]',
      colorName: 'GA12C5-K',
      colorGroup:'brown',
    },
    {
      colorNumber:93,
      colorPot:'bg-[#ddc9aa]',
      colorName: 'GA12C4-T',
      colorGroup:'brown',
    },
    {
      colorNumber:94,
      colorPot:'bg-[#bb9f78]',
      colorName: 'GA12C3-D',
      colorGroup:'brown',
    },
    {
      colorNumber:95,
      colorPot:'bg-[#95774f]',
      colorName: 'GA12C2-A',
      colorGroup:'brown',
    },
    {
      colorNumber:96,
      colorPot:'bg-[#846746]',
      colorName: 'GA12C1-A',
      colorGroup:'brown',
    },
    {
      colorNumber:97,
      colorPot:'bg-[#fffbf4]',
      colorName: 'GA13C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:98,
      colorPot:'bg-[#fef8e4]',
      colorName: 'GA13C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:99,
      colorPot:'bg-[#faefd2]',
      colorName: 'GA13C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:100,
      colorPot:'bg-[#f4e9cc]',
      colorName: 'GA13C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:101,
      colorPot:'bg-[#decda8]',
      colorName: 'GA13C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:102,
      colorPot:'bg-[#c3a46a]',
      colorName: 'GA13C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:103,
      colorPot:'bg-[#b49457]',
      colorName: 'GA13C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:104,
      colorPot:'bg-[#927f4e]',
      colorName: 'GA13C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:105,
      colorPot:'bg-[#fffdfa]',
      colorName: 'GA14C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:106,
      colorPot:'bg-[#fffffb]',
      colorName: 'GA14C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:107,
      colorPot:'bg-[#fff8df]',
      colorName: 'GA14C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:108,
      colorPot:'bg-[#f9ecc8]',
      colorName: 'GA14C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:109,
      colorPot:'bg-[#ebd5ab]',
      colorName: 'GA14C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:110,
      colorPot:'bg-[#ceac6c]',
      colorName: 'GA14C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:111,
      colorPot:'bg-[#bf9858]',
      colorName: 'GA14C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:112,
      colorPot:'bg-[#a98a50]',
      colorName: 'GA14C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:113,
      colorPot:'bg-[#fefbee]',
      colorName: 'GA15C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:114,
      colorPot:'bg-[#fefbee]',
      colorName: 'GA15C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:115,
      colorPot:'bg-[#fef6e0]',
      colorName: 'GA15C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:116,
      colorPot:'bg-[#ffe7bb]',
      colorName: 'GA15C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:117,
      colorPot:'bg-[#ffdc9d]',
      colorName: 'GA15C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:118,
      colorPot:'bg-[#e2b97d]',
      colorName: 'GA15C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:119,
      colorPot:'bg-[#dcaa62]',
      colorName: 'GA15C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:120,
      colorPot:'bg-[#cd9e5b]',
      colorName: 'GA15C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:121,
      colorPot:'bg-[#fffdf7]',
      colorName: 'GA16C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:122,
      colorPot:'bg-[#fefae9]',
      colorName: 'GA16C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:123,
      colorPot:'bg-[#fff7d3]',
      colorName: 'GA16C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:124,
      colorPot:'bg-[#fdefb7]',
      colorName: 'GA16C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:125,
      colorPot:'bg-[#f7d789]',
      colorName: 'GA16C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:126,
      colorPot:'bg-[#f8d589]',
      colorName: 'GA16C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:127,
      colorPot:'bg-[#ecc062]',
      colorName: 'GA16C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:128,
      colorPot:'bg-[#ecbc5d]',
      colorName: 'GA16C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:129,
      colorPot:'bg-[#fffdf7]',
      colorName: 'GA17C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:130,
      colorPot:'bg-[#fefcee]',
      colorName: 'GA17C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:131,
      colorPot:'bg-[#fdfad9]',
      colorName: 'GA17C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:132,
      colorPot:'bg-[#fef7c8]',
      colorName: 'GA17C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:133,
      colorPot:'bg-[#fdf0b3]',
      colorName: 'GA17C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:134,
      colorPot:'bg-[#fddd7f]',
      colorName: 'GA17C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:135,
      colorPot:'bg-[#fed14d]',
      colorName: 'GA17C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:136,
      colorPot:'bg-[#f8c949]',
      colorName: 'GA17C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:137,
      colorPot:'bg-[#fffdf7]',
      colorName: 'GA18C8-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:138,
      colorPot:'bg-[#fefbeb]',
      colorName: 'GA18C7-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:139,
      colorPot:'bg-[#fdfbe4]',
      colorName: 'GA18C6-P',
      colorGroup:'yellow',
    },
    {
      colorNumber:140,
      colorPot:'bg-[#fdf9d1]',
      colorName: 'GA18C5-K',
      colorGroup:'yellow',
    },
    {
      colorNumber:141,
      colorPot:'bg-[#fcf6a9]',
      colorName: 'GA18C4-T',
      colorGroup:'yellow',
    },
    {
      colorNumber:142,
      colorPot:'bg-[#fbed85]',
      colorName: 'GA18C3-D',
      colorGroup:'yellow',
    },
    {
      colorNumber:143,
      colorPot:'bg-[#fbe249]',
      colorName: 'GA18C2-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:144,
      colorPot:'bg-[#fed54b]',
      colorName: 'GA18C1-A',
      colorGroup:'yellow',
    },
    {
      colorNumber:145,
      colorPot:'bg-[#f7fcfa]',
      colorName: 'GA19C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:146,
      colorPot:'bg-[#f0f9f5]',
      colorName: 'GA19C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:147,
      colorPot:'bg-[#ebf6ed]',
      colorName: 'GA19C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:148,
      colorPot:'bg-[#e9f3dc]',
      colorName: 'GA19C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:149,
      colorPot:'bg-[#dfedc8]',
      colorName: 'GA19C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:150,
      colorPot:'bg-[#c4dfa1]',
      colorName: 'GA19C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:151,
      colorPot:'bg-[#a7c771]',
      colorName: 'GA19C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:152,
      colorPot:'bg-[#92b066]',
      colorName: 'GA19C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:153,
      colorPot:'bg-[#f9fdfb]',
      colorName: 'GA20C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:154,
      colorPot:'bg-[#f3f9f5]',
      colorName: 'GA20C7-A',
      colorGroup:'green',
    },
    {
      colorNumber:155,
      colorPot:'bg-[#ebf6eb]',
      colorName: 'GA20C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:156,
      colorPot:'bg-[#ddecd7]',
      colorName: 'GA20C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:157,
      colorPot:'bg-[#cee6c6]',
      colorName: 'GA20C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:158,
      colorPot:'bg-[#afce97]',
      colorName: 'GA20C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:159,
      colorPot:'bg-[#9bbc6f]',
      colorName: 'GA20C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:160,
      colorPot:'bg-[#8db06f]',
      colorName: 'GA20C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:161,
      colorPot:'bg-[#fdfdfb]',
      colorName: 'GA21C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:162,
      colorPot:'bg-[#f7fbf7]',
      colorName: 'GA21C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:163,
      colorPot:'bg-[#eef7ef]',
      colorName: 'GA21C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:164,
      colorPot:'bg-[#d8ebda]',
      colorName: 'GA21C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:165,
      colorPot:'bg-[#c8dec9]',
      colorName: 'GA21C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:166,
      colorPot:'bg-[#a6c79a]',
      colorName: 'GA21C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:167,
      colorPot:'bg-[#85a965]',
      colorName: 'GA21C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:168,
      colorPot:'bg-[#779f69]',
      colorName: 'GA21C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:169,
      colorPot:'bg-[#f8fcfc]',
      colorName: 'GA22C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:170,
      colorPot:'bg-[#edf7f6]',
      colorName: 'GA22C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:171,
      colorPot:'bg-[#ebf6f5]',
      colorName: 'GA22C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:172,
      colorPot:'bg-[#cae0da]',
      colorName: 'GA22C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:173,
      colorPot:'bg-[#b2cdc4]',
      colorName: 'GA22C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:174,
      colorPot:'bg-[#86a292]',
      colorName: 'GA22C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:175,
      colorPot:'bg-[#67846c]',
      colorName: 'GA22C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:176,
      colorPot:'bg-[#5e7965]',
      colorName: 'GA22C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:177,
      colorPot:'bg-[#f9fdfc]',
      colorName: 'GA23C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:178,
      colorPot:'bg-[#f2f9f7]',
      colorName: 'GA23C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:179,
      colorPot:'bg-[#e8f5f2]',
      colorName: 'GA23C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:180,
      colorPot:'bg-[#dbeee8]',
      colorName: 'GA23C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:181,
      colorPot:'bg-[#c0d8d0]',
      colorName: 'GA23C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:182,
      colorPot:'bg-[#8ba096]',
      colorName: 'GA23C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:183,
      colorPot:'bg-[#6c8070]',
      colorName: 'GA23C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:184,
      colorPot:'bg-[#647b6f]',
      colorName: 'GA23C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:185,
      colorPot:'bg-[#f2fafb]',
      colorName: 'GA24C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:186,
      colorPot:'bg-[#eff8f6]',
      colorName: 'GA24C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:187,
      colorPot:'bg-[#ebf6f2]',
      colorName: 'GA24C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:188,
      colorPot:'bg-[#d6eae0]',
      colorName: 'GA24C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:189,
      colorPot:'bg-[#c3d7cf]',
      colorName: 'GA24C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:190,
      colorPot:'bg-[#91a99d]',
      colorName: 'GA24C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:191,
      colorPot:'bg-[#677b6b]',
      colorName: 'GA24C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:192,
      colorPot:'bg-[#616f68]',
      colorName: 'GA24C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:193,
      colorPot:'bg-[#f9f9fa]',
      colorName: 'GA25C8-P',
      colorGroup:'green',
    },
    {
      colorNumber:194,
      colorPot:'bg-[#eff4f5]',
      colorName: 'GA25C7-P',
      colorGroup:'green',
    },
    {
      colorNumber:195,
      colorPot:'bg-[#dfe8e7]',
      colorName: 'GA25C6-P',
      colorGroup:'green',
    },
    {
      colorNumber:196,
      colorPot:'bg-[#dbe2e1]',
      colorName: 'GA25C5-K',
      colorGroup:'green',
    },
    {
      colorNumber:197,
      colorPot:'bg-[#cedad7]',
      colorName: 'GA25C4-T',
      colorGroup:'green',
    },
    {
      colorNumber:198,
      colorPot:'bg-[#a9bbb7]',
      colorName: 'GA25C3-D',
      colorGroup:'green',
    },
    {
      colorNumber:199,
      colorPot:'bg-[#7b8f85]',
      colorName: 'GA25C2-A',
      colorGroup:'green',
    },
    {
      colorNumber:200,
      colorPot:'bg-[#748480]',
      colorName: 'GA25C1-A',
      colorGroup:'green',
    },
    {
      colorNumber:201,
      colorPot:'bg-[#ebf0f1]',
      colorName: 'GA26C8-P',
      colorGroup:'blue',
    },
    {
      colorNumber:202,
      colorPot:'bg-[#dfe8e8]',
      colorName: 'GA26C7-P',
      colorGroup:'blue',
    },
    {
      colorNumber:203,
      colorPot:'bg-[#d6dedf]',
      colorName: 'GA26C6-P',
      colorGroup:'blue',
    },
    {
      colorNumber:204,
      colorPot:'bg-[#bfcccc]',
      colorName: 'GA26C5-K',
      colorGroup:'blue',
    },
    {
      colorNumber:205,
      colorPot:'bg-[#a2b4b6]',
      colorName: 'GA26C4-T',
      colorGroup:'blue',
    },
    {
      colorNumber:206,
      colorPot:'bg-[#809c9d]',
      colorName: 'GA26C3-D',
      colorGroup:'blue',
    },
    {
      colorNumber:207,
      colorPot:'bg-[#4d7d7f]',
      colorName: 'GA26C2-A',
      colorGroup:'blue',
    },
    {
      colorNumber:208,
      colorPot:'bg-[#5c747a]',
      colorName: 'GA26C1-A',
      colorGroup:'blue',
    },
    {
      colorNumber:209,
      colorPot:'bg-[#ebf2f6]',
      colorName: 'GA27C8-P',
      colorGroup:'blue',
    },
    {
      colorNumber:210,
      colorPot:'bg-[#e4edf1]',
      colorName: 'GA27C7-P',
      colorGroup:'blue',
    },
    {
      colorNumber:211,
      colorPot:'bg-[#d0dfe7]',
      colorName: 'GA27C6-P',
      colorGroup:'blue',
    },
    {
      colorNumber:212,
      colorPot:'bg-[#bcd1db]',
      colorName: 'GA27C5-K',
      colorGroup:'blue',
    },
    {
      colorNumber:213,
      colorPot:'bg-[#a6c3d1]',
      colorName: 'GA27C4-A',
      colorGroup:'blue',
    },
    {
      colorNumber:214,
      colorPot:'bg-[#a4acb0]',
      colorName: 'GA27C3-D',
      colorGroup:'blue',
    },
    {
      colorNumber:215,
      colorPot:'bg-[#7b8a90]',
      colorName: 'GA27C2-A',
      colorGroup:'blue',
    },
    {
      colorNumber:216,
      colorPot:'bg-[#4c738a]',
      colorName: 'GA27C1-A',
      colorGroup:'blue',
    },
    {
      colorNumber:217,
      colorPot:'bg-[#eff5f9]',
      colorName: 'GA28C8-P',
      colorGroup:'blue',
    },
    {
      colorNumber:218,
      colorPot:'bg-[#e6f0f8]',
      colorName: 'GA28C7-P',
      colorGroup:'blue',
    },
    {
      colorNumber:219,
      colorPot:'bg-[#e2edf7]',
      colorName: 'GA28C6-P',
      colorGroup:'blue',
    },
    {
      colorNumber:220,
      colorPot:'bg-[#bfdaf0]',
      colorName: 'GA28C5-K',
      colorGroup:'blue',
    },
    {
      colorNumber:221,
      colorPot:'bg-[#95c0e5]',
      colorName: 'GA28C4-T',
      colorGroup:'blue',
    },
    {
      colorNumber:222,
      colorPot:'bg-[#6e9ed3]',
      colorName: 'GA28C3-D',
      colorGroup:'blue',
    },
    {
      colorNumber:223,
      colorPot:'bg-[#1e79be]',
      colorName: 'GA28C2-A',
      colorGroup:'blue',
    },
    {
      colorNumber:224,
      colorPot:'bg-[#1775a9]',
      colorName: 'GA28C1-A',
      colorGroup:'blue',
    },
    {
      colorNumber:225,
      colorPot:'bg-[#f2f7fa]',
      colorName: 'GA29C8-P',
      colorGroup:'blue',
    },
    {
      colorNumber:226,
      colorPot:'bg-[#e6f0f8]',
      colorName: 'GA29C7-P',
      colorGroup:'blue',
    },
    {
      colorNumber:227,
      colorPot:'bg-[#d9e9f6]',
      colorName: 'GA29C6-P',
      colorGroup:'blue',
    },
    {
      colorNumber:228,
      colorPot:'bg-[#bdd8f0]',
      colorName: 'GA29C5-K',
      colorGroup:'blue',
    },
    {
      colorNumber:229,
      colorPot:'bg-[#8dc0e7]',
      colorName: 'GA29C4-T',
      colorGroup:'blue',
    },
    {
      colorNumber:230,
      colorPot:'bg-[#65b0e0]',
      colorName: 'GA29C3-D',
      colorGroup:'blue',
    },
    {
      colorNumber:231,
      colorPot:'bg-[#1582bc]',
      colorName: 'GA29C2-A',
      colorGroup:'blue',
    },
    {
      colorNumber:232,
      colorPot:'bg-[#1b7097]',
      colorName: 'GA29C1-A',
      colorGroup:'blue',
    },
    {
      colorNumber:233,
      colorPot:'bg-[#f2f7fb]',
      colorName: 'GA30C8-P',
      colorGroup:'blue',
    },
    {
      colorNumber:234,
      colorPot:'bg-[#e7f3f9]',
      colorName: 'GA30C7-P',
      colorGroup:'blue',
    },
    {
      colorNumber:235,
      colorPot:'bg-[#daedf7]',
      colorName: 'GA30C6-P',
      colorGroup:'blue',
    },
    {
      colorNumber:236,
      colorPot:'bg-[#b7dff2]',
      colorName: 'GA30C5-K',
      colorGroup:'blue',
    },
    {
      colorNumber:237,
      colorPot:'bg-[#9fcbeb]',
      colorName: 'GA30C4-T',
      colorGroup:'blue',
    },
    {
      colorNumber:238,
      colorPot:'bg-[#77bae5]',
      colorName: 'GA30C3-D',
      colorGroup:'blue',
    },
    {
      colorNumber:239,
      colorPot:'bg-[#3978a3]',
      colorName: 'GA30C2-A',
      colorGroup:'blue',
    },
    {
      colorNumber:240,
      colorPot:'bg-[#1a6482]',
      colorName: 'GA30C1-A',
      colorGroup:'blue',
    },
  ]
}
  this.handleClick = this.handleClick.bind(this)
}
  handleClick(event){
    this.setState({varColor:event.target.value})
  }

  render(){
    const filterColor = this.state.colorCodes.filter(color => {
      if(this.state.varColor==='') return color
      return color.colorGroup === this.state.varColor
    })
    const renderColors = filterColor.map((color,index) =>
      <div className={`border rounded-2xl relative w-[100%] aspect-[3/2] ${color.colorPot}`} key={index}>
        <p className='absolute bottom-0 left-0 p-2'>
        {color.colorName}<br />({color.colorNumber})
        </p>
      </div>
    )

  return(
  <>
    <div className='bannerContainer'>
      <Banner
      sendImg='./img/backgroundtheme.jpg'
      sendAlt='roxo banner background'
      />
    </div>
    <TitleCenter name='Bảng màu sơn Roxo'/>
    <Button onClick={this.handleClick} value='black'>Black</Button>
    <Button onClick={this.handleClick} value='red'>Red</Button>
    <Button onClick={this.handleClick} value='brown'>Brown</Button>
    <Button onClick={this.handleClick} value='yellow'>Yellow</Button>
    <Button onClick={this.handleClick} value='green'>Green</Button>
    <Button onClick={this.handleClick} value='blue'>Blue</Button>
    <Button onClick={this.handleClick} value=''>All</Button>
    <div className='p-4 grid grid-cols-8 gap-1 w-[100%]'>{renderColors}</div>

  </>
  )
}
}
export default ColorPalettePage
